# Generated by Django 2.2.16 on 2022-03-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220324_1300'),
        ('reviews', '0004_auto_20220324_1548'),
        ('reviews', '0004_auto_20220324_1056'),
    ]

    operations = [
    ]
